name: CI

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v2
      with:
       name: bluubomb_nightly
       path: |
        bluubomb
        sd_kernels/sd_kernels.zip
